// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgvgepejudzykpbaexnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxndmdlcGVqdWR6eWtwYmFleG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzMwODgsImV4cCI6MjA2MzIwOTA4OH0.vgX6b8cEC64b9Cb6NPbr6DUK1AadpLHi47o6fYm3Vxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);